package com.kcpc.mkt.common.error;

/**
 * Governed domain error codes surfaced in API error responses (API_Specification.md §26/§30).
 * Extended as later phases introduce their own domain errors.
 */
public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS,
    AUTH_ACCOUNT_INACTIVE,
    AUTH_TOKEN_MISSING,
    AUTH_TOKEN_INVALID,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_REVOKED,
    AUTH_CSRF_INVALID,
    PERM_ACCESS_CLASS_DENIED,
    PERM_OPERATIONAL_PERMISSION_REQUIRED,
    PERM_OPERATIONAL_PERMISSION_EXPIRED,
    PERM_OPERATIONAL_PERMISSION_OUT_OF_SCOPE,
    PERM_SELF_APPROVAL_PROHIBITED,
    PERM_DELEGATION_PROHIBITED,
    RESOURCE_NOT_FOUND,
    VALIDATION_FAILED,
    WORKFLOW_INVALID_TRANSITION,
    WORKFLOW_ACTIVE_HOLD_BLOCKS_ACTION,
    CONFLICT_DUPLICATE_SUBMISSION,
    CONFLICT_STALE_UPDATE
}
